DROP TABLESPACE DATA_REPRESENTATION INCLUDING CONTENTS CASCADE CONSTRAINTS; 
/
CREATE TABLESPACE DATA_REPRESENTATION
  DATAFILE 'data_representation_perm_0001.dat' 
    SIZE 500M
    REUSE
    AUTOEXTEND ON NEXT 50M MAXSIZE 2000M
/
CREATE TEMPORARY TABLESPACE DATA_REPRESENTATION
  TEMPFILE 'data_representation_temp_0001.dbf'
    SIZE 5M
    AUTOEXTEND ON
/    
CREATE UNDO TABLESPACE DATA_REPRESENTATION
  DATAFILE 'data_representation_undo_0001.dbf'
    SIZE 5M 
    AUTOEXTEND ON
  RETENTION GUARANTEE
/

drop user DATA_REPRESENTATION cascade;
/
create user DATA_REPRESENTATION identified by DATA_REPRESENTATION;
/
alter user DATA_REPRESENTATION default DATA_REPRESENTATION chess quota 1990M on DATA_REPRESENTATION;
/
grant connect to DATA_REPRESENTATION;
/
grant all privileges to DATA_REPRESENTATION;


